#!/bin/bash

echo "Making sure project is clean"
./gradlew clean

echo "Runnig Gradlew Test"
./gradlew test

createdb testing1234 && echo -e "Database successfully created" && psql -d  testing1234  < testscript.sql && echo "Tables created successfully"



#echo "Building your project"
#./gradlew build
#
#./gradlew create
#
#cd build/scripts
#
#./gradle-travis-sample