#!/bin/bash

echo "Making sure project is clean"
./gradlew clean

echo "Runnig Gradlew Test"
./gradlew test

echo "Building your project"
./gradlew build

./gradlew create

cd build/scripts

./gradle-travis-sample